# DATA SCIENCE WEEK 01 ASSIGNMENT

##### 1.	Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

Matrisler satır ve sütunlardan oluşan iki boyutlu dizilere denilmektedir. Matrisler tek satır veya tek sütundan meydana geldiğinde buna vektör veya tek boyutlu dizi adı verilmektedir. 

##### 2.	10 elemanli bir listeden NumPy Array’i olusturunuz.

In [3]:
import numpy as np

list_2 = list(range(1,11))
array_2 = np.array(list_2)
array_2


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### 3.	Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [4]:
array_3 = np.zeros((10,10), dtype="int32")
array_3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

##### 4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [9]:
array_4 = np.ones((10,10))
array_4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

##### 5. Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [11]:
array_5 = np.full((10,10),9)
array_5

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

##### 6. 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [12]:
array_6 = np.arange(5,25,3)
array_6

array([ 5,  8, 11, 14, 17, 20, 23])

##### 7.	-1 ile 1 arasinda 30 adet Array olusturunuz.

In [14]:
array_7 = np.linspace(-1,1,30) #30 adet sayının arasında eşit mesafe oluyor.
array_7

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

##### 8.	0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [16]:
array_8 = np.random.randint(0,30,(5,6))
array_8

array([[ 5,  0, 16,  6, 12,  5],
       [15,  9, 25, 22, 17, 26],
       [16, 13, 13, 21, 27, 28],
       [10, 14, 22,  7, 12, 26],
       [11, 28,  1, 23, 23, 13]])

##### 9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 

In [18]:
array_9 = np.eye(10)
array_9

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

##### 10.	0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
a.	eleman sayisini
b.	boyut bilgisini/sayisini
c.	satir X sutun bilgisini
d.	veri tipini numpy metodlariyla yazdiriniz.


In [22]:
array_10 = np.random.randint(0,10,(5,10))
array_10

array([[1, 6, 4, 7, 7, 4, 8, 1, 0, 0],
       [3, 7, 0, 5, 8, 3, 4, 4, 4, 2],
       [9, 9, 0, 7, 2, 3, 1, 5, 6, 2],
       [2, 5, 6, 7, 5, 9, 4, 8, 8, 7],
       [9, 7, 0, 1, 5, 8, 5, 5, 4, 3]])

In [23]:
print("\na) ", array_10.size, "\nb) ", array_10.ndim, "\nc) ", array_10.shape, "\nd) ", array_10.dtype)


a)  50 
b)  2 
c)  (5, 10) 
d)  int32


##### 11.	0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak) 

In [24]:
array_11 = np.random.randint(0,10, (3,4,7))
array_11

array([[[0, 3, 2, 9, 7, 6, 9],
        [0, 9, 2, 6, 8, 2, 8],
        [8, 3, 2, 3, 7, 2, 3],
        [8, 3, 4, 2, 0, 4, 5]],

       [[3, 3, 2, 0, 4, 1, 9],
        [2, 2, 5, 4, 1, 7, 2],
        [5, 0, 4, 3, 2, 7, 8],
        [9, 4, 0, 7, 2, 5, 9]],

       [[1, 9, 3, 1, 7, 0, 0],
        [2, 7, 1, 3, 4, 1, 6],
        [4, 8, 6, 0, 2, 3, 3],
        [3, 5, 5, 5, 4, 5, 8]]])

##### 12.	Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [69]:
array_12 = np.array([3,5,7,9])
rs_12 = array_12.reshape((2,2))
rs_12


array([[3, 5],
       [7, 9]])

#### 13.	4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [30]:
array_13_a = np.array(list(range(4)))
array_13_b = np.array(list(range(4,7)))
array_13_c = np.array(list(range(7,10)))
array_13_d = np.array(list(range(10,13)))

array_13 = np.concatenate([array_13_a, array_13_b, array_13_c, array_13_d])
array_13

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

##### 14.	2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [35]:
array_14_a = np.array([[1,2],[3,4]])
array_14_b = np.array([[11,12,13,14],
                      [15,16,17,18]])

array_14 = np.hstack([array_14_a, array_14_b])
array_14

array([[ 1,  2, 11, 12, 13, 14],
       [ 3,  4, 15, 16, 17, 18]])

##### 15.	Numpy’da “axis=1” ve “axis=0”  arasinda ne fark vardir. Teorik olarak yaziniz?  

concatenate fonksiyonunun default değerinde axis=0 'dır. axis=0 iken array'leri satır bazlı birleştirirken, axis=1 olarak değiştirildiğinde sütun bazlı birleştirme işlemi yapılır.

##### 16.	Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

In [73]:
array_16_a = np.array([0,1,2,3]) #tek boyutlu 1x4
array_16_b = np.array([[4,5,6],
                       [7,8,9]]) #iki boyutlu 2x3

In [77]:
array_16_a1 = array_16_a.reshape((2,2))
# sütun bazlı birleştirebilmek için şeklini değiştirdik. ikisinin satır sayılarının aynı olması lazım.
hs_16 = np.hstack([array_16_a1, array_16_b])
hs_16


array([[0, 1, 4, 5, 6],
       [2, 3, 7, 8, 9]])

In [78]:
array_16_a2 = array_16_a.reshape(4,1) 
array_16_b2 = array_16_b.reshape(6,1) 
# satır bazlı birleştirebilmek için şekillerini değiştirdik. ikisinin sütun sayılarının aynı olması lazım.
vs_16 = np.vstack([array_16_a2, array_16_b2])
vs_16

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

##### 17.	10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [79]:
array_17 = list(range(1,11))

array_17 = np.split(array_17, [4,6,9]) #köşeli parantez içindeki sayılar kaçıncı indexlerden bölüneceğini gösteriyor.
array_17

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9]), array([10])]

##### 18.	Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [88]:
array_18 = np.random.randint(10,20,5)
array_18 = np.sort(array_18)
array_18

array([10, 12, 13, 15, 16])

In [90]:
ind = 1
for i in array_18:
    print(f"{ind}. sıradaki eleman: {i} ")
    ind += 1

1. sıradaki eleman: 10 
2. sıradaki eleman: 12 
3. sıradaki eleman: 13 
4. sıradaki eleman: 15 
5. sıradaki eleman: 16 


##### 19.	20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [92]:
array_19 = np.random.randint(0,100, size=20)
array_19

array([26, 70, 27, 80, 50, 49, 21, 97, 45, 65, 70, 64, 43, 31, 13, 72, 55,
       45,  2,  4])

In [94]:
array_19[2], array_19[4], array_19[6]

(27, 50, 21)

##### 20.	10 elemanli random bir vektor olusturunuz ve bu arrayin  4. elemanini farkli bir sayiyla degistiriniz.

In [95]:
array_20 = np.random.randint(0,100, size=10)
array_20

array([42, 20, 70, 49, 64, 18, 83, 96, 26, 36])

In [96]:
array_20[3] = 999
array_20

array([ 42,  20,  70, 999,  64,  18,  83,  96,  26,  36])

##### 21.	“Diagonal Matrix” ve “Trace Matrix”  kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

Birim matris köşegeni üzerindeki elemanları (1) olan matrise denilir. Köşegen matris (diagonal) ise sadece köşegeni üzerinde değer bulunan diğer elemanları sıfır (0) olan matrise denilmektedir.

Bir A n-kare matrisinin a11, a22, ..., ann elemanlarına köşegen elemanları, bu elemanların toplamına da A nın izi (trace) denir.

##### 22.	5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [99]:
array_22 = np.eye(5)
array_22

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [100]:
array_22[0,0], array_22[1,1], array_22[2,2], array_22[3,3], array_22[4,4]

(1.0, 1.0, 1.0, 1.0, 1.0)

##### 23.	10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [101]:
array_23 = np.arange(10,20)
array_23[3:]

array([13, 14, 15, 16, 17, 18, 19])

##### 24.	10X10 luk bir matris olusturunuz ve ;
 .	3.satir ve 5.sutuna ulasiniz.
a.	5.sutunun tum satirlarina ulasiniz.
b.	Tum sutunlarin 2.satirlarina ulasiniz.
c.	tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
d.	satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
e.	satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
f.	sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
g.	5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 


In [4]:
array_24 = np.random.randint(10,100, (10,10))
array_24

array([[26, 46, 53, 29, 20, 14, 36, 25, 97, 63],
       [25, 67, 20, 36, 65, 17, 91, 83, 26, 14],
       [56, 24, 88, 68, 46, 42, 52, 41, 31, 43],
       [88, 84, 53, 86, 31, 72, 64, 67, 34, 26],
       [72, 66, 82, 88, 83, 42, 35, 41, 29, 45],
       [59, 61, 73, 90, 47, 15, 81, 87, 73, 60],
       [24, 28, 30, 66, 90, 58, 34, 14, 29, 98],
       [71, 15, 84, 88, 92, 78, 27, 76, 12, 84],
       [60, 79, 64, 23, 60, 49, 67, 14, 30, 56],
       [61, 87, 41, 31, 50, 54, 78, 14, 60, 89]])

In [5]:
array_24[2,4]

46

In [6]:
array_24[:,4] #a

array([20, 65, 46, 31, 83, 47, 90, 92, 60, 50])

In [7]:

array_24[1,:] #b

array([25, 67, 20, 36, 65, 17, 91, 83, 26, 14])

In [8]:
array_24[1:7,:] #c

array([[25, 67, 20, 36, 65, 17, 91, 83, 26, 14],
       [56, 24, 88, 68, 46, 42, 52, 41, 31, 43],
       [88, 84, 53, 86, 31, 72, 64, 67, 34, 26],
       [72, 66, 82, 88, 83, 42, 35, 41, 29, 45],
       [59, 61, 73, 90, 47, 15, 81, 87, 73, 60],
       [24, 28, 30, 66, 90, 58, 34, 14, 29, 98]])

In [9]:
array_24[1:5,2:7] #d

array([[20, 36, 65, 17, 91],
       [88, 68, 46, 42, 52],
       [53, 86, 31, 72, 64],
       [82, 88, 83, 42, 35]])

In [10]:
array_24[4:,:4] #e

array([[72, 66, 82, 88],
       [59, 61, 73, 90],
       [24, 28, 30, 66],
       [71, 15, 84, 88],
       [60, 79, 64, 23],
       [61, 87, 41, 31]])

In [12]:
array_24[:,(3,6,9)] #f

array([[29, 36, 63],
       [36, 91, 14],
       [68, 52, 43],
       [86, 64, 26],
       [88, 35, 45],
       [90, 81, 60],
       [66, 34, 98],
       [88, 27, 84],
       [23, 67, 56],
       [31, 78, 89]])

In [13]:
array_24[5,5] = 1991
array_24

array([[  26,   46,   53,   29,   20,   14,   36,   25,   97,   63],
       [  25,   67,   20,   36,   65,   17,   91,   83,   26,   14],
       [  56,   24,   88,   68,   46,   42,   52,   41,   31,   43],
       [  88,   84,   53,   86,   31,   72,   64,   67,   34,   26],
       [  72,   66,   82,   88,   83,   42,   35,   41,   29,   45],
       [  59,   61,   73,   90,   47, 1991,   81,   87,   73,   60],
       [  24,   28,   30,   66,   90,   58,   34,   14,   29,   98],
       [  71,   15,   84,   88,   92,   78,   27,   76,   12,   84],
       [  60,   79,   64,   23,   60,   49,   67,   14,   30,   56],
       [  61,   87,   41,   31,   50,   54,   78,   14,   60,   89]])

##### 25.	0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
 .	20 den buyuk olan kac deger var.
a.	30’dan kucuk kac deger var
b.	icerisinde 33 gecen kac deger var
c.	olusturulan arrayin tum elemanlarini 5 ile carpin.
d.	olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.


In [14]:
array_25 = np.arange(0,50,5)
array_25

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
sum(array_25 > 20) #.

5

In [16]:
sum(array_25 < 30) #a

6

In [17]:
sum(array_25 == 33) #b

0

In [18]:
array_25 * 5 #c

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [19]:
array_25 % 2 #d

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

##### 26.	0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
 .	orlamasini aliniz.
a.	standart sapmasini aliniz.
b.	varyansini aliniz.
c.	median’ini aliniz.
d.	en kucuk degeri bulunuz.
e.	en buyuk degeri bulunuz.


In [20]:
array_26 = np.linspace(0,1,50)
array_26

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [21]:
np.mean(array_26) #.

0.5

In [22]:
np.std(array_26) #a

0.2945075446869757

In [23]:
np.var(array_26) #b

0.086734693877551

In [24]:
np.median(array_26) #c

0.5

In [25]:
np.min(array_26) #d

0.0

In [26]:
np.max(array_26) #e

1.0

## Master odev ; 
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin.
Ve fark matrisinin diagonali,  -0.1 ile 0.1  arasinda olana kadar bu islemi tekrarlayin.
Istenilen matris bulundugunda program dursun ve  toplam kac dongunun kuruldugunu,  ne kadar sure icinde buldugunu ve  istenilen  matrisi  print ile birlikte ekrana yazdiriniz...
Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.
Matris uretme islemini np.random.random((axb)) fonksiyonu ile yapabilirsiniz.(size kalmis)


In [1]:
import numpy as np
import time

start = time.time()
meter = 1
while True:
    a = np.random.random((5, 5))
    b = np.random.random((5, 5))
    c = a - b
    d = c.diagonal()

    if sum((-0.1 < d) & (d < 0.1)) == 5:
        print(c, "\n")
        print(d, "\n")
        end = time.time()
        print(f"Time: {end-start}, \nLoop: {meter}")
        break
    meter += 1
    
#Bu döngüde 20x20 saatlerce çalıştı ancak sonuç vermedi. Bu yüzden 5x5 i paylaşıyorum.

[[-0.06061093  0.44121717  0.01079226 -0.38754147  0.09303769]
 [ 0.36949744 -0.03550856 -0.51840554 -0.19710236 -0.05120132]
 [-0.0630952  -0.02344335 -0.09316355 -0.45303231 -0.18660758]
 [-0.41249565  0.44289876  0.08250692  0.02729242  0.22234545]
 [ 0.10273674  0.00455515  0.03597756 -0.70489566 -0.0594657 ]] 

[-0.06061093 -0.03550856 -0.09316355  0.02729242 -0.0594657 ] 

Time: 0.33424973487854004, 
Loop: 11352
